import type { Metadata } from "next";
import { type FC } from "react";
import "../globals.css";
import HeaderContainer from "@/containers/Header/Header.container";
import SidebarContainer from "@/containers/SideBar/SideBar.container";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <ThemeProvider
      attribute="data-theme"
      defaultTheme="spring"
      enableSystem={false}
      themes={["spring", "summer", "autumn", "winter"]}
    >
      <HeaderContainer />
      <main className="main">
        <SidebarContainer />
        {children}
      </main>
    </ThemeProvider>
  );
};

export default MainLayout;
