import type { Metadata } from "next";
import { type FC } from "react";
import "../globals.css";
import HeaderContainer from "@/containers/Header/Header.container";
import SidebarContainer from "@/containers/Sidebar/Sidebar.container";
import { ThemeProvider } from "next-themes";
import UserProvider from "@/providers/User.providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <ThemeProvider
      attribute="data-theme"
      defaultTheme="spring"
      enableSystem={false}
      themes={["spring", "summer", "autumn", "winter"]}
    >
      <UserProvider>
        <HeaderContainer />
        <main className="main">
          <SidebarContainer />
          {children}
        </main>
      </UserProvider>
    </ThemeProvider>
  );
};

export default MainLayout;
