import type { Metadata } from "next";
import { type FC } from "react";
import styles from "./layout.module.css";
import classNames from "classnames/bind";

const cx = classNames.bind(styles);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LoginLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return <div className={cx("login-layout")}>{children}</div>;
};

export default LoginLayout;
