import type { Metadata } from "next";
import { type FC } from "react";
import "./globals.css";
import AlertModalContainer from "@/containers/Modals/AlertModal/AlertModal.container";
import ConfirmModalContainer from "@/containers/Modals/ConfirmModal/ConfirmModal.container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        {children}
        <ConfirmModalContainer />
      </body>
    </html>
  );
};

export default RootLayout;
