import type { Metadata } from "next";
import { type FC } from "react";
import "./globals.css";
import HeaderContainer from "@/containers/Header/Header.container";
import SidebarContainer from "@/containers/Sidebar/Sidebar.container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="ko">
      <body>
        <HeaderContainer />
        <main className="main">
          <SidebarContainer />
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
